apiVersion: apps/v1
kind: Deployment
metadata:
  name: fenrir-backend
spec:
  selector:
    matchLabels:
      app: fenrir-backend
  template:
    metadata:
      labels:
        app: fenrir-backend
    spec:
      containers:
      - name: fenrir-backend
        image: docker.io/sid2672/tutedude-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: mongo
          value: "http://mongodb:27017/"

---

apiVersion: v1
kind: Service
metadata:
  name: fenrir-backend
spec:
  selector:
    app: fenrir-backend
  ports:
  - port: 8000
    targetPort: 8000
