apiVersion: apps/v1
kind: Deployment
metadata:
  name: fenrir-frontend
spec:
  selector:
    matchLabels:
      app: fenrir-frontend
  template:
    metadata:
      labels:
        app: fenrir-frontend
    spec:
      containers:
      - name: fenrir-frontend
        image: docker.io/sid2672/tutedude-frontend:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: fenrir-frontend
spec:
  selector:
    app: fenrir-frontend
  ports:
  - port: 9000
    targetPort: 5000

